// © 2026 DoctoPal — All Rights Reserved
import React from "react";
import { Document, Page, Text, View, StyleSheet, Font } from "@react-pdf/renderer";

// Sprint 20 Commit 2 — Helvetica + fixTr() (SBARReport paterni mirror).
// NotoSans 4+ yaklaşım Vercel serverless'da fail oldu. Helvetica built-in +
// Turkish ASCII transliteration: ş→s/ğ→g/ü→u/ö→o/ç→c/ı→i/İ→I (büyük harfler de).
// Sprint 21+'da CDN font veya @react-pdf/renderer upgrade ile NotoSans dönüşü.
const fixTr = (s: string): string => {
  if (!s) return "";
  return s
    .replace(/ı/g, "i").replace(/İ/g, "I")
    .replace(/ş/g, "s").replace(/Ş/g, "S")
    .replace(/ğ/g, "g").replace(/Ğ/g, "G")
    .replace(/ü/g, "u").replace(/Ü/g, "U")
    .replace(/ö/g, "o").replace(/Ö/g, "O")
    .replace(/ç/g, "c").replace(/Ç/g, "C");
};
Font.registerHyphenationCallback((word) => [word]);

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 10, color: "#1a1a1a" },
  header: { borderBottom: "2px solid #2563eb", paddingBottom: 12, marginBottom: 20 },
  title: { fontSize: 18, fontFamily: "Helvetica-Bold", color: "#2563eb" },
  subtitle: { fontSize: 10, color: "#6b7280", marginTop: 4 },
  urgencyBanner: { padding: 12, borderRadius: 4, marginBottom: 16 },
  urgencyNormal: { backgroundColor: "#f0fdf4", color: "#166534" },
  urgencyAttention: { backgroundColor: "#fefce8", color: "#854d0e" },
  urgencyUrgent: { backgroundColor: "#fef2f2", color: "#991b1b" },
  sectionTitle: { fontSize: 13, fontFamily: "Helvetica-Bold", color: "#2563eb", marginTop: 16, marginBottom: 8, borderBottom: "1px solid #d1d5db", paddingBottom: 4 },
  finding: { marginBottom: 10, padding: 8, backgroundColor: "#f8fafc", borderRadius: 4 },
  findingRegion: { fontFamily: "Helvetica-Bold", fontSize: 11, marginBottom: 3 },
  findingText: { fontSize: 9, color: "#374151", marginBottom: 2 },
  glossaryItem: { marginBottom: 6 },
  glossaryTerm: { fontFamily: "Helvetica-Bold", fontSize: 10 },
  glossaryDef: { fontSize: 9, color: "#374151" },
  disclaimer: { marginTop: 20, padding: 12, backgroundColor: "#fef2f2", borderRadius: 4, fontSize: 8, color: "#991b1b", lineHeight: 1.4 },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, flexDirection: "row", justifyContent: "space-between", fontSize: 8, color: "#9ca3af", borderTop: "0.5px solid #e5e7eb", paddingTop: 8 },
  listItem: { marginBottom: 4, paddingLeft: 10, fontSize: 9, color: "#374151" },
  bullet: { fontFamily: "Helvetica-Bold", color: "#2563eb" },
});

interface Finding {
  region: string;
  observation: string;
  medicalTerm: string;
  significance: string;
  explanation: string;
}

interface GlossaryItem {
  term: string;
  definition: string;
}

interface Analysis {
  imageType: string;
  overallUrgency: string;
  summary: string;
  findings: Finding[];
  glossary: GlossaryItem[];
  doctorDiscussion: string[];
  limitations: string[];
  disclaimer: string;
}

interface RadiologyReportProps {
  analysis: Analysis;
  lang?: "tr" | "en";
}

export function RadiologyReport({ analysis, lang = "en" }: RadiologyReportProps) {
  // Sprint 16 — locale-aware string bundle. Sprint 20 Commit 2 — TR branch fixTr wrap.
  const t = {
    title: lang === "tr" ? fixTr("DoctoPal — Radyoloji Analiz Raporu") : "DoctoPal — Radiology Analysis Report",
    subtitle: lang === "tr"
      ? fixTr("Eğitim Amaçlı Radyolojik Görüntü Yorumu | Sağlık Profesyoneli İncelemesi İçin")
      : "Educational Radiology Image Interpretation | For Healthcare Provider Review",
    findings: lang === "tr" ? fixTr("Bulgular") : "Findings",
    glossary: lang === "tr" ? fixTr("Tıbbi Terimler Sözlüğü") : "Medical Glossary",
    doctor: lang === "tr" ? fixTr("Doktorunuzla Konuşun") : "Discussion Points for Your Doctor",
    limitations: lang === "tr" ? fixTr("Analiz Sınırları") : "Analysis Limitations",
    disclaimer: lang === "tr" ? fixTr("ÖNEMLİ UYARI") : "IMPORTANT DISCLAIMER",
    urgency: lang === "tr" ? fixTr("Aciliyet") : "Urgency",
    modality: lang === "tr" ? fixTr("Modalite") : "Modality",
    medicalTerm: lang === "tr" ? fixTr("Tıbbi terim") : "Medical term",
    defaultDisclaimer: lang === "tr"
      ? fixTr("Bu rapor DoctoPal tarafından eğitim amaçlı oluşturulmuştur. Radyolojik tanı DEĞİLDİR. Tüm tıbbi görüntüler nitelikli bir radyolog tarafından yorumlanmalıdır. Daima sağlık profesyoneline danışın.")
      : "This report is generated by DoctoPal for educational purposes only. It is NOT a radiological diagnosis. A qualified radiologist must interpret all medical images. Always consult your healthcare provider.",
    footer: lang === "tr" ? fixTr("DoctoPal tarafından oluşturuldu | doctopal.com") : "Generated by DoctoPal | doctopal.com",
  };

  const date = new Date().toLocaleDateString(lang === "tr" ? "tr-TR" : "en-US", {
    year: "numeric", month: "long", day: "numeric",
  });
  const urgencyStyle = analysis.overallUrgency === "urgent" ? styles.urgencyUrgent
    : analysis.overallUrgency === "attention" ? styles.urgencyAttention
    : styles.urgencyNormal;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{t.title}</Text>
          <Text style={styles.subtitle}>{t.subtitle}</Text>
        </View>

        <View style={[styles.urgencyBanner, urgencyStyle]}>
          <Text style={{ fontFamily: "Helvetica-Bold", marginBottom: 4 }}>
            {t.urgency}: {analysis.overallUrgency.toUpperCase()} | {t.modality}: {analysis.imageType.toUpperCase()}
          </Text>
          <Text>{fixTr(analysis.summary)}</Text>
        </View>

        <Text style={styles.sectionTitle}>{t.findings}</Text>
        {analysis.findings.map((f, i) => (
          <View key={i} style={styles.finding}>
            <Text style={styles.findingRegion}>{fixTr(f.region)} — {f.significance.toUpperCase()}</Text>
            <Text style={styles.findingText}>{fixTr(f.observation)}</Text>
            <Text style={styles.findingText}>{t.medicalTerm}: {fixTr(f.medicalTerm)}</Text>
            <Text style={styles.findingText}>{fixTr(f.explanation)}</Text>
          </View>
        ))}

        {analysis.glossary.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>{t.glossary}</Text>
            {analysis.glossary.map((g, i) => (
              <View key={i} style={styles.glossaryItem}>
                <Text style={styles.glossaryTerm}>{fixTr(g.term)}</Text>
                <Text style={styles.glossaryDef}>{fixTr(g.definition)}</Text>
              </View>
            ))}
          </>
        )}

        {analysis.doctorDiscussion.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>{t.doctor}</Text>
            {analysis.doctorDiscussion.map((point, i) => (
              <View key={i} style={styles.listItem}>
                <Text><Text style={styles.bullet}>{i + 1}. </Text>{fixTr(point)}</Text>
              </View>
            ))}
          </>
        )}

        {analysis.limitations.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>{t.limitations}</Text>
            {analysis.limitations.map((lim, i) => (
              <View key={i} style={styles.listItem}>
                <Text><Text style={styles.bullet}>• </Text>{fixTr(lim)}</Text>
              </View>
            ))}
          </>
        )}

        <View style={styles.disclaimer}>
          <Text style={{ fontFamily: "Helvetica-Bold", marginBottom: 4 }}>{t.disclaimer}</Text>
          <Text>{fixTr(analysis.disclaimer) || t.defaultDisclaimer}</Text>
        </View>

        <View style={styles.footer}>
          <Text>{t.footer}</Text>
          <Text>{fixTr(date)}</Text>
        </View>
      </Page>
    </Document>
  );
}
