// © 2026 DoctoPal — All Rights Reserved
import { NextRequest, NextResponse } from "next/server";
import { Resend } from "resend";
import { createServerClient } from "@/lib/supabase";
import { checkRateLimit, getClientIP } from "@/lib/rate-limit";
import { sanitizeInput } from "@/lib/sanitize";

const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;

export const maxDuration = 30;

export async function POST(request: NextRequest) {
  try {
    const clientIP = getClientIP(request);
    const rateCheck = checkRateLimit(`sbar-email:${clientIP}`, 5, 86_400_000); // 5 per day
    if (!rateCheck.allowed) {
      return NextResponse.json({ error: "Daily email limit reached (5/day)" }, { status: 429 });
    }

    if (!resend) {
      return NextResponse.json({ error: "Email service not configured" }, { status: 503 });
    }

    const authHeader = request.headers.get("authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return NextResponse.json({ error: "Authentication required" }, { status: 401 });
    }

    const token = authHeader.replace("Bearer ", "");
    const supabase = createServerClient();
    const { data: { user } } = await supabase.auth.getUser(token);
    if (!user) {
      return NextResponse.json({ error: "Invalid token" }, { status: 401 });
    }

    let body: Record<string, unknown>;
    try { body = await request.json(); } catch {
      return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
    }

    const recipientEmail = sanitizeInput((body.email as string) || "");
    const patientName = sanitizeInput((body.patientName as string) || "");
    const lang = (body.lang === "tr" ? "tr" : "en") as "en" | "tr";
    const pdfBase64 = body.pdfBase64 as string;

    if (!recipientEmail || !recipientEmail.includes("@")) {
      return NextResponse.json({ error: "Valid email required" }, { status: 400 });
    }
    if (!pdfBase64) {
      return NextResponse.json({ error: "PDF data required" }, { status: 400 });
    }

    const pdfBuffer = Buffer.from(pdfBase64, "base64");
    const dateStr = new Date().toLocaleDateString(lang === "tr" ? "tr-TR" : "en-US", { year: "numeric", month: "long", day: "numeric" });

    const subject = lang === "tr"
      ? `SBAR Hasta Raporu — DoctoPal (${dateStr})`
      : `SBAR Patient Report — DoctoPal (${dateStr})`;

    const html = `
      <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 640px; margin: 0 auto; background: #f8faf8; padding: 0;">
        <!-- Header -->
        <div style="background: linear-gradient(135deg, #3c7a52, #4a9a65); padding: 28px 32px; border-radius: 12px 12px 0 0;">
          <table width="100%" cellpadding="0" cellspacing="0"><tr>
            <td><span style="font-size: 24px; font-weight: 700; color: #ffffff; letter-spacing: -0.5px;">DoctoPal</span></td>
            <td align="right"><span style="font-size: 12px; color: rgba(255,255,255,0.8);">SBAR Report</span></td>
          </tr></table>
        </div>

        <!-- Body -->
        <div style="background: #ffffff; padding: 32px; border-left: 1px solid #e5e7eb; border-right: 1px solid #e5e7eb;">
          <p style="font-size: 15px; color: #1f2937; margin: 0 0 20px 0;">
            ${lang === "tr" ? "Sayın Doktor," : "Dear Doctor,"}
          </p>

          <p style="font-size: 14px; color: #374151; line-height: 1.7; margin: 0 0 20px 0;">
            ${lang === "tr"
              ? `Hastanız${patientName ? ` <strong>${patientName}</strong>` : ""}in yapılandırılmış SBAR (Situation-Background-Assessment-Recommendation) sağlık özet raporu ekte sunulmuştur. Bu rapor, hastanın mevcut sağlık durumu, ilaç kullanımı, alerji bilgileri ve yaşam tarzı verilerini içermektedir.`
              : `Please find attached the structured SBAR (Situation-Background-Assessment-Recommendation) health summary report for your patient${patientName ? ` <strong>${patientName}</strong>` : ""}. This report includes the patient's current health status, medication usage, allergy information, and lifestyle data.`
            }
          </p>

          <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 16px; margin: 0 0 24px 0;">
            <p style="font-size: 13px; color: #166534; margin: 0; font-weight: 600;">
              ${lang === "tr" ? "Ek: SBAR Raporu (PDF)" : "Attachment: SBAR Report (PDF)"}
            </p>
            <p style="font-size: 12px; color: #15803d; margin: 4px 0 0 0;">
              ${lang === "tr" ? `Oluşturulma tarihi: ${dateStr}` : `Generated on: ${dateStr}`}
            </p>
          </div>

          <p style="font-size: 13px; color: #6b7280; line-height: 1.6; margin: 0;">
            ${lang === "tr"
              ? "Bu rapor DoctoPal platformu aracılığıyla hasta tarafından oluşturulmuştur. Tıbbi karar süreçlerinde yardımcı bilgi olarak kullanılabilir."
              : "This report was generated by the patient through the DoctoPal platform. It can be used as supplementary information in clinical decision-making."
            }
          </p>
        </div>

        <!-- Footer -->
        <div style="background: #f9fafb; padding: 20px 32px; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 12px 12px;">
          <p style="font-size: 11px; color: #9ca3af; margin: 0; line-height: 1.6;">
            ${lang === "tr"
              ? "Bu rapor tıbbi teşhis veya reçete niteliği taşımaz. Profesyonel tıbbi değerlendirme yerine geçmez."
              : "This report does not constitute a medical diagnosis or prescription. It does not replace professional medical evaluation."
            }
          </p>
          <p style="font-size: 11px; color: #9ca3af; margin: 8px 0 0 0;">
            <a href="https://doctopal.com" style="color: #3c7a52; text-decoration: none;">doctopal.com</a>
          </p>
        </div>
      </div>
    `;

    await resend.emails.send({
      from: "DoctoPal <onboarding@resend.dev>",
      to: [recipientEmail],
      subject,
      html,
      attachments: [{
        filename: `DoctoPal-SBAR-${new Date().toISOString().split("T")[0]}.pdf`,
        content: pdfBuffer,
      }],
      tags: [{ name: "category", value: "sbar-report" }],
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("SBAR email error:", error);
    return NextResponse.json({ error: "Failed to send email" }, { status: 500 });
  }
}
