// © 2026 DoctoPal — All Rights Reserved
"use client"

import { useState, useEffect, useCallback } from "react"
import { useRouter } from "next/navigation"
import { useAuth } from "@/lib/auth-context"
import { useLang } from "@/components/layout/language-toggle"
import { tx } from "@/lib/translations"
import { createBrowserClient } from "@/lib/supabase"
import {
  QrCode,
  Download,
  Printer,
  Eye,
  LogIn,
  Loader2,
  User,
  Pill,
  AlertTriangle,
  Phone,
  TestTube2,
  Clock,
  Check,
} from "lucide-react"
import { Button } from "@/components/ui/button"

interface MedItem { brand_name: string | null; generic_name: string | null; dosage: string | null }
interface AllergyItem { allergen: string; severity: string }
interface LabResult { test_data: Record<string, unknown>; created_at: string }

const EXPIRY_OPTIONS = [
  { key: "24h", hours: 24 },
  { key: "7d", hours: 168 },
  { key: "30d", hours: 720 },
  { key: "never", hours: 0 },
] as const

export default function QRProfilePage() {
  const router = useRouter()
  const { user, profile, isAuthenticated, isLoading } = useAuth()
  const { lang } = useLang()

  const [medications, setMedications] = useState<MedItem[]>([])
  const [allergies, setAllergies] = useState<AllergyItem[]>([])
  const [latestLab, setLatestLab] = useState<LabResult | null>(null)
  const [loading, setLoading] = useState(true)

  // Checkboxes
  const [includeBasic, setIncludeBasic] = useState(true)
  const [includeMeds, setIncludeMeds] = useState(true)
  const [includeAllergies, setIncludeAllergies] = useState(true)
  const [includeEmergency, setIncludeEmergency] = useState(true)
  const [includeLabs, setIncludeLabs] = useState(false)

  const [expiry, setExpiry] = useState<string>("7d")
  const [showPreview, setShowPreview] = useState(false)
  const [generated, setGenerated] = useState(false)
  const [emergencyContact, setEmergencyContact] = useState({ name: "", phone: "" })

  const fetchData = useCallback(async () => {
    if (!user) return
    const supabase = createBrowserClient()
    setLoading(true)

    const [{ data: meds }, { data: allrg }, { data: labs }] = await Promise.all([
      supabase.from("user_medications").select("brand_name, generic_name, dosage").eq("user_id", user.id).eq("is_active", true),
      supabase.from("user_allergies").select("allergen, severity").eq("user_id", user.id),
      supabase.from("blood_tests").select("test_data, created_at").eq("user_id", user.id).order("created_at", { ascending: false }).limit(1),
    ])

    setMedications(meds || [])
    setAllergies(allrg || [])
    setLatestLab(labs?.[0] || null)

    // Load emergency contact from localStorage
    try {
      const cached = localStorage.getItem("phyto_emergency_cache")
      if (cached) {
        const d = JSON.parse(cached)
        if (d.emergencyContact) setEmergencyContact(d.emergencyContact)
      }
    } catch { /* ignore */ }

    setLoading(false)
  }, [user])

  useEffect(() => {
    if (!isLoading && !isAuthenticated) router.push("/auth/login")
  }, [isLoading, isAuthenticated, router])

  useEffect(() => {
    if (user) fetchData()
  }, [user, fetchData])

  const buildQRContent = () => {
    const lines: string[] = []
    const expiryOpt = EXPIRY_OPTIONS.find(o => o.key === expiry)
    if (expiryOpt && expiryOpt.hours > 0) {
      const expiresAt = new Date(Date.now() + expiryOpt.hours * 3600000)
      lines.push(`[Expires: ${expiresAt.toISOString().split("T")[0]}]`)
    }

    if (includeBasic) {
      lines.push("--- BASIC INFO ---")
      if (profile?.full_name) lines.push(`Name: ${profile.full_name}`)
      if (profile?.age) lines.push(`Age: ${profile.age}`)
      if (profile?.gender) lines.push(`Gender: ${profile.gender}`)
      if (profile?.blood_group) lines.push(`Blood: ${profile.blood_group}`)
    }

    if (includeMeds && medications.length > 0) {
      lines.push("--- MEDICATIONS ---")
      medications.forEach(m => {
        lines.push(`- ${m.brand_name || m.generic_name || "Unknown"}${m.dosage ? ` (${m.dosage})` : ""}`)
      })
    }

    if (includeAllergies && allergies.length > 0) {
      lines.push("--- ALLERGIES ---")
      allergies.forEach(a => {
        lines.push(`- ${a.allergen} [${a.severity}]`)
      })
    }

    if (includeEmergency && emergencyContact.name) {
      lines.push("--- EMERGENCY CONTACT ---")
      lines.push(`${emergencyContact.name}: ${emergencyContact.phone}`)
    }

    if (includeLabs && latestLab) {
      lines.push("--- LATEST LAB ---")
      lines.push(`Date: ${new Date(latestLab.created_at).toLocaleDateString()}`)
      const data = latestLab.test_data
      Object.entries(data).slice(0, 8).forEach(([key, val]) => {
        lines.push(`${key}: ${String(val)}`)
      })
    }

    lines.push("", "Generated by Doctopal")
    return lines.join("\n")
  }

  const qrContent = buildQRContent()
  const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(qrContent)}`

  const handleDownload = async () => {
    try {
      const response = await fetch(qrUrl)
      const blob = await response.blob()
      const url = URL.createObjectURL(blob)
      const a = document.createElement("a")
      a.href = url
      a.download = "doctopal-health-qr.png"
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    } catch { /* download failed */ }
  }

  const handlePrint = () => {
    const printWindow = window.open("", "_blank")
    if (printWindow) {
      printWindow.document.write(`
        <html><head><title>Health QR Code</title>
        <style>body{margin:0;display:flex;align-items:center;justify-content:center;min-height:100vh;font-family:system-ui}
        .wrap{text-align:center;padding:40px}
        h2{margin-bottom:8px}p{color:#666;font-size:14px}
        img{margin:20px auto;display:block}
        .info{max-width:400px;margin:16px auto;padding:16px;border:1px solid #ddd;border-radius:12px;text-align:left;font-size:13px;white-space:pre-wrap;color:#333}
        </style></head><body>
        <div class="wrap">
          <h2>Health Profile QR Code</h2>
          <p>Doctopal</p>
          <img src="${qrUrl}" width="250" height="250" />
          <div class="info">${qrContent.replace(/\n/g, "<br>")}</div>
        </div></body></html>
      `)
      printWindow.document.close()
      printWindow.print()
    }
  }

  if (isLoading) {
    return (
      <div className="flex min-h-[60vh] items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    )
  }

  if (!isAuthenticated) {
    return (
      <div className="min-h-[60vh] flex items-center justify-center p-4">
        <div className="text-center max-w-md">
          <QrCode className="w-12 h-12 text-primary mx-auto mb-4" />
          <h1 className="text-2xl font-bold mb-2">{tx("qrProfile.title", lang)}</h1>
          <p className="text-muted-foreground mb-6">{tx("qrProfile.loginRequired", lang)}</p>
          <Button onClick={() => router.push("/auth/login")} className="gap-2">
            <LogIn className="w-4 h-4" />
            {tx("tool.loginRequired", lang)}
          </Button>
        </div>
      </div>
    )
  }

  return (
    <div className="mx-auto max-w-2xl px-4 md:px-8 py-8">
      {/* Header */}
      <div className="text-center mb-8">
        <div className="w-14 h-14 bg-primary/10 rounded-2xl flex items-center justify-center mx-auto mb-3">
          <QrCode className="w-7 h-7 text-primary" />
        </div>
        <h1 className="text-2xl font-bold tracking-tight sm:text-3xl">{tx("qrProfile.title", lang)}</h1>
        <p className="mt-1 text-sm text-muted-foreground">{tx("qrProfile.subtitle", lang)}</p>
      </div>

      {loading ? (
        <div className="flex justify-center py-12">
          <Loader2 className="h-6 w-6 animate-spin text-primary" />
        </div>
      ) : (
        <div className="space-y-6">
          {/* Selection Checkboxes */}
          <div className="rounded-2xl border bg-card p-5 space-y-3">
            <h3 className="font-semibold text-sm">{tx("qrProfile.selectData", lang)}</h3>

            <CheckboxRow icon={<User className="h-4 w-4 text-blue-500" />} label={tx("qrProfile.basicInfo", lang)} sublabel={tx("qrProfile.basicInfoDesc", lang)} checked={includeBasic} onChange={setIncludeBasic} />
            <CheckboxRow icon={<Pill className="h-4 w-4 text-green-500" />} label={tx("qrProfile.medications", lang)} sublabel={`${medications.length} ${tx("qrProfile.active", lang)}`} checked={includeMeds} onChange={setIncludeMeds} disabled={medications.length === 0} />
            <CheckboxRow icon={<AlertTriangle className="h-4 w-4 text-amber-500" />} label={tx("qrProfile.allergies", lang)} sublabel={`${allergies.length} ${tx("qrProfile.recorded", lang)}`} checked={includeAllergies} onChange={setIncludeAllergies} disabled={allergies.length === 0} />
            <CheckboxRow icon={<Phone className="h-4 w-4 text-red-500" />} label={tx("qrProfile.emergencyContact", lang)} sublabel={emergencyContact.name || tx("qrProfile.notSet", lang)} checked={includeEmergency} onChange={setIncludeEmergency} disabled={!emergencyContact.name} />
            <CheckboxRow icon={<TestTube2 className="h-4 w-4 text-purple-500" />} label={tx("qrProfile.labResults", lang)} sublabel={latestLab ? new Date(latestLab.created_at).toLocaleDateString() : tx("qrProfile.noLabs", lang)} checked={includeLabs} onChange={setIncludeLabs} disabled={!latestLab} />
          </div>

          {/* Expiry Option */}
          <div className="rounded-2xl border bg-card p-5">
            <div className="flex items-center gap-2 mb-3">
              <Clock className="h-4 w-4 text-muted-foreground" />
              <h3 className="font-semibold text-sm">{tx("qrProfile.expiry", lang)}</h3>
            </div>
            <div className="flex flex-wrap gap-2">
              {EXPIRY_OPTIONS.map(opt => (
                <button
                  key={opt.key}
                  onClick={() => setExpiry(opt.key)}
                  className={`px-4 py-2 rounded-xl text-sm font-medium border transition-colors ${
                    expiry === opt.key
                      ? "bg-primary text-primary-foreground border-primary"
                      : "bg-muted/50 hover:bg-muted border-transparent"
                  }`}
                >
                  {tx(`qrProfile.expiry.${opt.key}`, lang)}
                </button>
              ))}
            </div>
          </div>

          {/* Generate Button */}
          <Button
            onClick={() => { setGenerated(true); setShowPreview(true) }}
            className="w-full h-12 rounded-2xl text-base font-semibold gap-2"
            disabled={!includeBasic && !includeMeds && !includeAllergies && !includeEmergency && !includeLabs}
          >
            <QrCode className="h-5 w-5" />
            {tx("qrProfile.generate", lang)}
          </Button>

          {/* Generated QR + Preview */}
          {generated && (
            <div className="space-y-4 animate-in fade-in duration-500">
              {/* QR Code Display */}
              <div className="rounded-2xl border bg-card p-6 text-center">
                <div className="inline-block bg-white rounded-2xl p-4 shadow-sm">
                  <img src={qrUrl} alt="Health Profile QR" className="w-56 h-56 mx-auto" />
                </div>
                <p className="text-xs text-muted-foreground mt-3">
                  {tx("qrProfile.scanHint", lang)}
                </p>

                {/* Action Buttons */}
                <div className="flex justify-center gap-3 mt-4">
                  <Button onClick={handleDownload} variant="outline" className="gap-2 rounded-xl">
                    <Download className="h-4 w-4" />
                    {tx("qrProfile.download", lang)}
                  </Button>
                  <Button onClick={handlePrint} variant="outline" className="gap-2 rounded-xl">
                    <Printer className="h-4 w-4" />
                    {tx("qrProfile.print", lang)}
                  </Button>
                  <Button onClick={() => setShowPreview(!showPreview)} variant="outline" className="gap-2 rounded-xl">
                    <Eye className="h-4 w-4" />
                    {tx("qrProfile.preview", lang)}
                  </Button>
                </div>
              </div>

              {/* Preview Panel */}
              {showPreview && (
                <div className="rounded-2xl border bg-muted/30 p-5">
                  <h3 className="font-semibold text-sm mb-3 flex items-center gap-2">
                    <Eye className="h-4 w-4" />
                    {tx("qrProfile.previewTitle", lang)}
                  </h3>
                  <pre className="text-xs bg-background rounded-xl p-4 overflow-x-auto whitespace-pre-wrap font-mono text-muted-foreground leading-relaxed">
                    {qrContent}
                  </pre>
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  )
}

function CheckboxRow({
  icon,
  label,
  sublabel,
  checked,
  onChange,
  disabled = false,
}: {
  icon: React.ReactNode
  label: string
  sublabel: string
  checked: boolean
  onChange: (v: boolean) => void
  disabled?: boolean
}) {
  return (
    <label className={`flex items-center gap-3 p-3 rounded-xl border transition-colors cursor-pointer ${
      disabled ? "opacity-50 cursor-not-allowed" : checked ? "border-primary/30 bg-primary/5" : "border-transparent bg-muted/30 hover:bg-muted/50"
    }`}>
      <input
        type="checkbox"
        checked={checked && !disabled}
        onChange={(e) => !disabled && onChange(e.target.checked)}
        disabled={disabled}
        className="sr-only"
      />
      <div className={`w-5 h-5 rounded-md border-2 flex items-center justify-center shrink-0 transition-colors ${
        checked && !disabled ? "bg-primary border-primary" : "border-gray-300 dark:border-gray-600"
      }`}>
        {checked && !disabled && <Check className="h-3 w-3 text-white" />}
      </div>
      {icon}
      <div className="flex-1 min-w-0">
        <p className="text-sm font-medium">{label}</p>
        <p className="text-xs text-muted-foreground truncate">{sublabel}</p>
      </div>
    </label>
  )
}
