// © 2026 DoctoPal — All Rights Reserved
import { test, expect } from "@playwright/test";

// Pages NOT covered by existing pages.spec.ts
const MISSING_PAGES = [
  "/accessibility",
  "/anti-inflammatory",
  "/biomarker-trends",
  "/body-analysis",
  "/botanical-hub",
  "/caffeine-tracker",
  "/calendar",
  "/cancer-screening",
  "/cancer-support",
  "/cardiovascular-risk",
  "/checkup-planner",
  "/chronic-care",
  "/circadian-rhythm",
  "/clinical-tests",
  "/clinical-trials",
  "/contact",
  "/cross-allergy",
  "/dental-health",
  "/detox-facts",
  "/diabetic-foot",
  "/drug-info",
  "/emergency-id",
  "/emergency-mode",
  "/fasting-monitor",
  "/food-prep",
  "/genetic-risk",
  "/grief-support",
  "/gut-health",
  "/hair-nail-health",
  "/hajj-health",
  "/health-diary",
  "/health-goals",
  "/health-guides",
  "/health-news-verifier",
  "/health-quiz",
  "/health-radar",
  "/health-report-card",
  "/health-roadmap",
  "/health-timeline",
  "/healthy-recipes",
  "/hydration",
  "/interaction-map",
  "/intermittent-fasting",
  "/jet-lag",
  "/kidney-dashboard",
  "/liver-monitor",
  "/lung-monitor",
  "/medical-dictionary",
  "/medication-hub",
  "/menopause-panel",
  "/migraine-dashboard",
  "/new-parent-health",
  "/nutrition",
  "/offline",
  "/organ-transplant",
  "/polypharmacy",
  "/posture-ergonomics",
  "/pregnancy-tracker",
  "/prevention-hub",
  "/pricing",
  "/privacy",
  "/prospectus-reader",
  "/rare-diseases",
  "/rehabilitation",
  "/scan-medication",
  "/seasonal-health",
  "/security",
  "/side-effects",
  "/skin-health",
  "/sleep-analysis",
  "/snoring-apnea",
  "/stretching",
  "/student-health",
  "/supplement-guide",
  "/supplement-hub",
  "/terms",
  "/thyroid-dashboard",
  "/travel-health",
  "/vaccination",
  "/vaccine-tracker",
  "/womens-health",
  "/yoga-meditation",
];

for (const url of MISSING_PAGES) {
  test(`Page ${url} loads without crash`, async ({ page }) => {
    const response = await page.goto(url);
    expect(response?.status()).toBe(200);
    // No unhandled error boundary
    const errorCount = await page.locator("text=Something went wrong").count();
    expect(errorCount).toBe(0);
  });
}
